//! GorgeMacros —— Gorge native 类桥接层过程宏
//!
//! 对应 C# 参考实现中由 Roslyn 源生成器产出的 `AutoGenerated/` 桥接层。
//! 本 crate 提供两个属性宏，配合使用即可让一个普通 Rust 结构体成为
//! 可被 Gorge 虚拟机调用的 native 类：
//!
//! - `#[gorge_native_class(namespace = "...")]` 标注结构体，声明字段与注入器字段，
//!   生成类元数据（全名、字段类型计数）与字段读写辅助方法。
//! - `#[gorge_native_impl]` 标注 `impl` 块，其中方法用 `#[gorge_static]` /
//!   `#[gorge_method]` / `#[gorge_ctor]` 标注，生成 `NativeClass` trait 实现，
//!   按方法编号分派到用户编写的业务方法，并完成参数拆箱与返回值装箱。
//!
//! # 约定（详见 reports/native-id-alignment.md）
//! - 方法编号：静态方法与实例方法共享**同一个混合编号空间**，按 `impl` 块内
//!   声明顺序从 0 递增（对齐规则 M1/M2）。
//! - 构造方法：单独编号，按声明顺序从 0 递增（对齐规则 C1）。
//! - 对象参数/返回值：用对象 ID（`usize`）传递（用户决策），业务方法通过
//!   `NativeContext` 读取字段。
//! - 字段/注入器字段编号：按值类型分组，组内按声明顺序从 0 递增（对齐规则 F2/I1）。

mod class_macro;
mod impl_macro;
mod common;

use proc_macro::TokenStream;

/// 标注 native 类结构体，生成类元数据与字段访问辅助。
///
/// # 参数
/// - `namespace = "..."`：类所属命名空间（必填），与源码引用的全名前缀一致。
///
/// # 字段标注
/// - `#[gorge_field]`：声明为 Gorge 对象字段。
/// - `#[inject(default = <expr>)]`：声明对应的注入器字段，可选默认值。
///
/// # 自动派生
/// 宏会自动为结构体添加 `#[derive(Debug)]`（`NativeClass` 要求 `Debug`），
/// 因此**请勿手动 derive Debug**，否则会重复派生报错。
///
/// # 生成项
/// - `Self::GORGE_FULL_NAME`：类全名常量
/// - `Self::gorge_field_type_count()` / `gorge_injector_field_type_count()`
/// - `Self::FIELD_INDEX_<name>` / `Self::INJECTOR_INDEX_<name>`：字段索引常量
/// - `Self::gorge_injector_default_<name>()`：带默认值的注入器字段默认值
///
/// # 示例
/// ```ignore
/// #[gorge_native_class(namespace = "GorgeFramework")]
/// pub struct Vector2 {
///     #[gorge_field]
///     #[inject(default = 0.0)]
///     pub x: f32,
///     #[gorge_field]
///     #[inject(default = 0.0)]
///     pub y: f32,
/// }
/// ```
#[proc_macro_attribute]
pub fn gorge_native_class(attr: TokenStream, item: TokenStream) -> TokenStream {
    class_macro::expand(attr, item)
}

/// 标注 native 类的 `impl` 块，生成 `NativeClass` trait 实现。
///
/// 块内方法用以下属性之一标注（未标注的方法原样保留，作为内部辅助）：
/// - `#[gorge_static]`：静态方法，签名形如 `fn name(ctx, args...) -> Ret`。
/// - `#[gorge_method]`：实例方法，签名形如 `fn name(ctx, this: usize, args...) -> Ret`。
/// - `#[gorge_ctor]`：构造方法，签名形如 `fn name(ctx, this: usize, args...)`，
///   负责初始化 `this` 对象的字段。
///
/// # 参数与返回值类型映射
/// - `i32`/`i64` → int，`f32`/`f64` → float，`bool` → bool，
///   `String` → string，`usize` → object（对象 ID）。
///
/// # 参数约定
/// - 第一个参数必须是 `ctx: &mut NativeContext`（宏按「引用类型」识别并跳过）。
/// - 实例方法与构造方法需有名为 `this: usize` 的参数（宏按参数名跳过），表示目标对象 ID。
/// - 其余参数为值参数，按上表类型映射从参数池读取。
///
/// # 编号约定（详见 reports/native-id-alignment.md）
/// - 静态方法与实例方法共享同一混合编号空间，按声明顺序从 0 递增。
/// - 构造方法单独编号，按声明顺序从 0 递增。
///
/// # 注意
/// `NativeContext` 的对象字段访问器使用 VM 存储类型（`f64`/`i64`），
/// 业务方法若用 `f32`/`i32`，需在方法体内自行 `as` 转换。
#[proc_macro_attribute]
pub fn gorge_native_impl(attr: TokenStream, item: TokenStream) -> TokenStream {
    impl_macro::expand(attr, item)
}
